spring:
  application:
    name: config-api

  web:
    cors:
      mappings:
        "[/**]":
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/batch_engine
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # Liquibase maneja el schema, JPA solo valida
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8081

logging:
  level:
    com.batchengine: DEBUG
    liquibase: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true